# Base configs
baseurl: "http://photography.skpaik.net"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Sudipta K Paik"
subtitle: "See the world through my eyes!"
author: "Sudipta K Paik"
header:
 title: "Photography"
 subtitle: "by Sudipta K Paik"
footer:
 name: "Hey there, my name is Sudipta"
 bio: "I am a Software Engineer from Khulna, Bangladesh, Love Android and Photography most."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/skpaik/skpaik.github.io\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/skpaik"
  twitter: "https://www.twitter.com/skpaik"
  instagram: "https://www.instagram.com/skpaik"
  # dribbble: "https://dribbble.com/skpaik"
  linkedin: "https://in.linkedin.com/in/skpaik"
  github: "https://www.github.com/skpaik"
